
Vagrant.configure("2") do |config|
  config.vm.box = "LuisilloElPillo/CalculadoraThrift"
  config.vm.box_version = "0.0.1"
  config.vm.hostname ='spotyfei-dev-box'
  config.vm.synced_folder "./code/", "/vagrant"
  config.vm.boot_timeout = 60000000
end
